### ISSUE TITLE
[Bug]: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

### ISSUE THREAD

**Issue by luizjr** [jaegertracing/helm-charts#445]
### What happened?

Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/

My kubernetes version is 1.25.4

autoscaling | v1, v2, v2beta2
-- | --

### Steps to reproduce

helm upgrade --install jaeger -n jaeger jaegertracing/jaeger

### Expected behavior

Helm updated

### Jaeger backend version

v1.37.0

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell
helm upgrade --install jaeger -n jaeger jaegertracing/jaeger
```

**Comment by mehta-ankit** [comment]
@luizjr what is the chart version you are using ??
I thought this was fixed in https://github.com/jaegertracing/helm-charts/pull/439

**Comment by luizjr** [comment]
> @luizjr what is the chart version that you are using ?? I thought this was fixed in #439

I saw that it was, but I couldn't update, I had to reinstall!

But it's still not going up the collectors...
![image](https://user-images.githubusercontent.com/1474563/219147813-50b76aad-9aed-46bc-b2ab-db99c252e391.png)

**Comment by luizjr** [comment]
The key for Oauth2 was missing
I put it and it worked, but I only managed to reinstall from scratch. Update didn't work
